# Generated by Django 5.0 on 2023-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryCreated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('iamge', models.ImageField(blank=True, null=True, upload_to='created_history_imaes', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='OurValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ourvalues_images/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Principles_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='principleswork_images/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_iamages', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamge', models.ImageField(blank=True, null=True, upload_to='team_images/', verbose_name='Фото')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Звание')),
            ],
        ),
    ]
