# Generated by Django 5.0 on 2023-12-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historycreated',
            options={'verbose_name': 'Истории создание', 'verbose_name_plural': 'История создание'},
        ),
        migrations.AlterModelOptions(
            name='ourvalues',
            options={'verbose_name': 'Наши ценности', 'verbose_name_plural': 'Наш сенност'},
        ),
        migrations.AlterModelOptions(
            name='principles_work',
            options={'verbose_name': 'Принципы работы', 'verbose_name_plural': 'Принцип работы'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки баннера', 'verbose_name_plural': 'Настройка баннера'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Наши коаманда', 'verbose_name_plural': 'Команда'},
        ),
    ]
