# Generated by Django 5.0 on 2023-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('start', models.CharField(blank=True, max_length=255, null=True, verbose_name='Старт')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='Время')),
                ('graphik', models.CharField(max_length=255, verbose_name='График')),
                ('banner_descriptions', models.TextField(blank=True, max_length=600, null=True, verbose_name='Баннер Описание')),
                ('moth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Длительность')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('lessons', models.CharField(blank=True, max_length=255, null=True, verbose_name='Занятий')),
                ('teachers', models.CharField(max_length=255, verbose_name='Преподавателей')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание курса')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coureses_images/', verbose_name='Фотография')),
                ('start', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название курса')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Опсание')),
            ],
        ),
    ]
