# Generated by Django 5.0 on 2023-12-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'verbose_name': 'Добробне о курса', 'verbose_name_plural': 'Подробне о курса'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Добавить курс', 'verbose_name_plural': 'Добавить курс'},
        ),
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
