# Generated by Django 5.0 on 2023-12-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_tehnalogis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='cours',
            name='descriptions_1',
            field=models.TextField(blank=True, null=True, verbose_name='Описание курса 1'),
        ),
        migrations.AddField(
            model_name='cours',
            name='descriptions_2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание курса 2'),
        ),
    ]
