# Generated by Django 5.0 on 2023-12-09 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_cours_descriptions_cours_descriptions_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tehnalogis',
            name='frgkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.cours'),
            preserve_default=False,
        ),
    ]
