# Generated by Django 5.0 on 2023-12-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tehnalogis_frgkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='moth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Делительность курса'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Старт курсы'),
        ),
    ]
