# Generated by Django 5.0 on 2023-12-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_moth_alter_courses_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='frkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
            preserve_default=False,
        ),
    ]
