# Generated by Django 5.0 on 2023-12-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_remove_tehnalogis_frgkey_delete_cours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.CharField(default=1, max_length=255, verbose_name='Уроки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='moth',
            field=models.CharField(default=1, max_length=255, verbose_name='Делителность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(default=1, max_length=255, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='techers',
            field=models.CharField(default=1, max_length=255, verbose_name='Переподаватели'),
            preserve_default=False,
        ),
    ]
