# Generated by Django 5.0 on 2023-12-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_lessons_course_moth_course_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': ('Добавить курс',), 'verbose_name_plural': 'Добавить курс'},
        ),
        migrations.AlterField(
            model_name='course',
            name='about_course1',
            field=models.TextField(blank=True, null=True, verbose_name='Подроне о курса 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='about_course2',
            field=models.TextField(blank=True, null=True, verbose_name='Подроне о курса 1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='banner_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Баннер описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='graphics',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уроки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='moth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Делителность'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Старт курса'),
        ),
        migrations.AlterField(
            model_name='course',
            name='techers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Переподаватели'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время'),
        ),
    ]
