# Generated by Django 5.0 on 2023-12-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_course_options_alter_course_about_course1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='larning_img',
            field=models.ImageField(upload_to='course_images/', verbose_name='Фото что изучет'),
        ),
    ]
