# Generated by Django 5.0 on 2023-12-10 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_larning_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='larning_img',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learning_title',
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('larning_img', models.ImageField(upload_to='course_images/', verbose_name='Фото что изучет')),
                ('learning_title', models.CharField(max_length=255, verbose_name='Название')),
                ('frg_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name': ('Что изучает',),
                'verbose_name_plural': 'Что изучает',
            },
        ),
    ]
