# Generated by Django 5.0 on 2023-12-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_course_larning_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning',
            old_name='larning_img',
            new_name='learning_img',
        ),
    ]
