# Generated by Django 5.0 on 2023-12-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='history_images/', verbose_name='Первое фото')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='history_images/', verbose_name='Второе фото')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='GeeksInt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Geek в цифрах',
                'verbose_name_plural': 'Geeks в цифрах',
            },
        ),
        migrations.CreateModel(
            name='GeeksOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='geeksonline_images/', verbose_name='Фотография')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Сылка на страницу')),
            ],
        ),
        migrations.CreateModel(
            name='HowAreYou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, max_length=800, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Кем ты можеш стать после курса',
                'verbose_name_plural': 'Кем ты сожеш стать после курса',
            },
        ),
        migrations.CreateModel(
            name='LearningGeeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Почему стоить учиться в Geeks ?',
                'verbose_name_plural': 'Почему стоить учиться в Geeks ?',
            },
        ),
        migrations.CreateModel(
            name='StudentsProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='student_project_images/', verbose_name='Выаускные работы студентов')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Сылка на проект')),
            ],
        ),
    ]
