# Generated by Django 5.0 on 2023-12-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_settings_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksHistory',
        ),
        migrations.AlterModelOptions(
            name='studentsproject',
            options={'verbose_name': 'Выпускные работы стаудентов', 'verbose_name_plural': 'Выпускное работа студента '},
        ),
    ]
