# Generated by Django 5.0 on 2023-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='freelesson_images/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='GeekaJuniorCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iamge', models.ImageField(blank=True, null=True, upload_to='geeksjunior_images', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('start', models.CharField(blank=True, max_length=255, null=True, verbose_name='Старт')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('moth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Делительность')),
            ],
        ),
        migrations.CreateModel(
            name='HowJunior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Баннер загаловок')),
                ('banner_descriptions', models.TextField(blank=True, max_length=500, null=True, verbose_name='Баннер описание')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner_photo', verbose_name='Баннер описание')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
            ],
        ),
    ]
