# Generated by Django 5.0 on 2023-12-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeksjunior', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frelesson',
            options={'verbose_name': 'Пробный урок', 'verbose_name_plural': 'Пробный урок'},
        ),
        migrations.AlterModelOptions(
            name='geekajuniorcourses',
            options={'verbose_name': 'Курсы Geeks Junior', 'verbose_name_plural': 'Курс geeks junior'},
        ),
        migrations.AlterModelOptions(
            name='howjunior',
            options={'verbose_name': 'Почему стоит выбрать GeeksJunior', 'verbose_name_plural': 'Почему стоить выбрать Geeks Junior'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': ('Настройки баннера',), 'verbose_name_plural': 'Настройка баннера'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика '},
        ),
    ]
