# Generated by Django 5.0 on 2023-12-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksproFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='HowGeeksPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=800, verbose_name='Почему именно GeeksPro')),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Сылка')),
                ('iamge', models.ImageField(blank=True, null=True, upload_to='partner_images/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Баннер описание')),
                ('banner_descriptions', models.TextField(max_length=500, verbose_name='Бннер описание')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner_photos/', verbose_name='Баннер фото')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticGeekspro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Загаловок')),
                ('descriptions', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
            ],
        ),
    ]
