# Generated by Django 5.0 on 2023-12-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekspro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geeksprofaq',
            options={'verbose_name': 'Почему Geekspro', 'verbose_name_plural': 'Почему Geekspro'},
        ),
        migrations.AlterModelOptions(
            name='howgeekspro',
            options={'verbose_name': 'Почему Geekspro', 'verbose_name_plural': 'Почему Geekspro'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партеры', 'verbose_name_plural': 'Парноры  '},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки беннера', 'verbose_name_plural': 'Натройка баннера'},
        ),
        migrations.AlterModelOptions(
            name='statisticgeekspro',
            options={'verbose_name': 'Статистики', 'verbose_name_plural': 'Статистика'},
        ),
    ]
