# Generated by Django 5.0 on 2023-12-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksJuniorCoursPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная Почта')),
                ('cours', models.CharField(max_length=255, verbose_name='Выбирал курс')),
            ],
            options={
                'verbose_name': 'Записи на курсов Geeks Junior',
                'verbose_name_plural': 'Запись на курс Geeks Junior',
            },
        ),
        migrations.CreateModel(
            name='JuniorSelectCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Курсы на выбор Junior',
                'verbose_name_plural': 'Курс на выбор Junior',
            },
        ),
    ]
