# Generated by Django 5.0 on 2023-12-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0002_geeksjuniorcourspost_juniorselectcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksProdirections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Выбор направлении на Geeks Pro',
                'verbose_name_plural': 'Направление на Geeks Pro',
            },
        ),
        migrations.CreateModel(
            name='GeeksProPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер')),
                ('email', models.EmailField(max_length=255, verbose_name='Электронная Почта')),
                ('direction', models.CharField(max_length=255, verbose_name='Направление')),
                ('learning', models.CharField(max_length=255, verbose_name='Где училься')),
            ],
            options={
                'verbose_name': 'Заявки на Geeks Pro',
                'verbose_name_plural': 'Заявка на Geeks Pro',
            },
        ),
    ]
